name: psykube
type: Deployment
context: gke_commercial-tribe-staging_us-central1-a_staging
registry_user: commercialtribe

args: [ "playground", "--bind=0.0.0.0" ]
ports:
  http: 8080
ingress:
  tls: true
  host: psykube.commercialtribe.ninja
