version: 2
name: psykube
type: Deployment

image_pull_secrets:
  - server: quay.io
    username: {{ env.DOCKER_USERNAME }}
    password: {{ env.DOCKER_PASSWORD }}

registry_host: quay.io
registry_user: psykube
replicas: 5

ingress:
  tls: true
  host: playground.psykube.io

containers:
  playground:
    tag: {{ git.tag }}
    args: [ "playground", "--bind=0.0.0.0" ]
    ports:
      http: 8080
