sudo: required
language: crystal
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - docker-ce
env:
  global:
    - PSYKUBE_DEBUG=true
    - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PSYKUBE_CONTEXT=gke_waldrip-net_us-central1-a_waldrip-net

install: shards install

before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - echo ${GCLOUD_ENCODED_CREDS} | base64 -d > /tmp/gcloud.json
  - gcloud auth activate-service-account --key-file=/tmp/gcloud.json
  - gcloud container clusters get-credentials waldrip-net --zone=us-central1-a --project=waldrip-net

script: crystal spec --verbose
before_deploy:
  - 'shards build --release --no-debug'
  - 'tar -czC ./bin psykube > ./psykube-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz'
  - 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
deploy:
  -
    provider: releases
    skip_cleanup: true
    api_key:
      secure: lxW4Yi1u760t88HseNYRfLb7tIOuqCQZfjVC29ivAZa2i9Utb4yqrc+Q3bgXdcp55DzeiVcwpsUcYf5kgJCwzcrR2+DglYc7r2BBTvPhLABXkRBWA4CVILyblm7UWQAYjAB7VxzWV/IraiYhaPz+0WQsWPY1nQbIycsmHWjuKDe8awl8khA8VfoKj+H33dHwJkVfvKT97t+s6beXYKJ+Er/Y48rhaya2x8ebUiTlLpwYUDN8wrJHGDAuYEQrH5xNeS6PNHnOWLw6u/RYjtLeXjcXBw0b7SzhadrqwBwD4BxYWtnre/trPeVg2QkqNbZi2HF6uftCWKZM5b6I6wbJ5lRxisTdNdZujfmdW6UXw4oeHcR0YGv0g5imN0K0HVvBDSyelmfm1nfRvu0Tnm3KTsWXqXoVjO4ZaWdg4LOVgMH9arArK5sAsmzPvZpcOkRjKb4do8m4Y54XxQeU2/5VewX3BX0+BMXLAwlh3BQIDiNQtMdw+j/wuegvMgREhVmAthDVAVstkiW/PhP6c+TtkmgOQ00d812brt2qNYauGgHYdemkrtR/JL//9pZya65fKkpNnK0JpDCsfKiJc24w/XCruXMarbHXfYKz3mVarqYVQKB79VgtG7ff8ziMWI8IuJ8qlRqTBzfiAjHlZUru5p1nf92aZ8YYssU7y61fcZQ=
    file: ./psykube-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
    on:
      repo: psykube/psykube
      tags: true
  -
    provider: script
    skip_cleanup: true
    script: './bin/psykube apply'
    on:
      repo: psykube/psykube
      tags: true
  -
    provider: script
    skip_cleanup: true
    script: './bin/psykube push -t $TRAVIS_TAG -t latest'
    on:
      repo: psykube/psykube
      tags: true
