sudo: required
language: bash
install:
- "./bin/install-crystal"
- shards build
script:
- shards build
- crystal spec
before_deploy:
- shards build --release
- tar -czC ./bin psykube > ./psykube-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
deploy:
  provider: releases
  api_key:
    secure: HcSf5TGficOxL3WUUljSpnS9D7xKXFzp+JjXrjS9ruB5R1qTOUvX5t71MTuGsaYFFHDhUhSBmOcCc9P2toQVx+d69dn6nRbkOmf4m1+MZ4NKvkx5Nj8lWTxgkfUERM8y2XPdYtEphNQsgmByyMnq4XK2XC34FHWyHYo5CqyUqCcR4w3Q/Ye5UnIUYxl4AJZvYrxVZxPRLARSQxyQhvl4xVv+m7nYRrXULnB+Sdu9LECz+iEX7BkaRg0/AjTr47xcx955HWekPXdCFowEU5cqWybyf9UFZzs2Ryy7R4UyaVqY+LGv7E2uv9ItcWJC7JqxPeoIGWEbL3lfO8rMKwrnIK+HcGoy8xCuPIb5044zr7aUQrb4b5YVSAdmjYJku27cfAfA23K6iiT1+1gDKPdNlq/2L7XWf1cnP7OYuKeuF+x6nMRk9yyqYtI8xCtnk4415/HDgS1ruqI4DlRoiH5ZVSvhWAKXiDsUyMV7SV8MAKj5cNWg7mlsV95EVCK/JqveZI1vhrgdeWNri2jgPK6vXO98uvWYbjqY+SV2D+Tf02MPkjscHrF+9Cdghbaqux9zz7bisCfQBfnZkS+fZ34fE3sSjwyRm6DMNLHtSXoVfb3CQnesm/1EkghDlmF0e6Etrt7eFQCW30BVgGcTeCu3JKwdsjK3cZF07HVjr6d6Liw=
  file: "../psykube-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz"
  on:
    repo: CommercialTribe/psykube
