version: 2
name: test-app
registry_user: jwaldrip
context: gke_waldrip-net_us-central1-a_waldrip-net
containers:
  app:
    ports:
      http: 80

cron_jobs:
  hourly:
    schedule: 0 * * * *
    command: [echo, "its the top of the hour"]
jobs:
  migrate: echo "migrate"
ingress:
  tls: true
  annotations:
    kubernetes.io/tls-acme: "true"
clusters:
  staging:
    ingress:
      host: psykube-simple.{{metadata.namespace}}.waldrip.net
  production:
    ingress:
      host: psykube-simple.waldrip.net
    config_map:
      some.value: "tada"
